#
# Nufront Clock specific Makefile
#

obj-$(CONFIG_ARCH_NPSC01)	+= clk-pll.o
obj-$(CONFIG_ARCH_NPSC01)	+= clk-divider.o
obj-$(CONFIG_ARCH_NPSC01)	+= clk-cpu.o
obj-$(CONFIG_ARCH_NPSC01)	+= clk-npsc01.o
